name: example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  #Hive
  hive: ^2.2.3

  hive_flutter: ^1.1.0
  path_provider: ^2.0.8

  #SQFLite
  sqflite: ^2.2.8
  sqlite3: ^2.0.0

  #Isar
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0

  #Path
  path: ^1.8.2

  #New in town
  quantum_cache_db:
    path: ../

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

  isar_generator: ^3.1.0
  build_runner: ^2.3.3
