name: quantum_cache_db
description: "A fast, secure Dart & Flutter local database"
version: 0.0.1
homepage:

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  mutex: ^3.1.0
  archive: ^3.4.0
  crypto: ^3.0.3
  path: ^1.8.3
  uuid: ^4.3.3

  # Optional Flutter dependencies
  path_provider:
    optional: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.9
  mockito: ^5.4.4

# The following section is specific to Flutter packages.
flutter:
